### ISSUE TITLE
`kSecCSDynamicInformation` should not be returned for `SecStaticCode` objects according to Apple docs

### ISSUE THREAD

**Issue by balazserdeszlogmein** [securing/SimpleXPCApp#2]
Hi, I would just like to point out a potential mistake in the `ConnectionVerifier` class.

Apple [documentation](kSecCSDynamicInformation) on `kSecCSDynamicInformation` says:

> This information cannot be returned for code on disk (represented by a [SecStaticCode](doc://com.apple.documentation/documentation/security/secstaticcode?language=swift) object).

Yet the ConnectionVerifier builds a `SecStaticCode` object, and tries to retrieve the `kSecCSDynamicInformation` flag for it. Could you please let me know if this is OK, or is something that's not gonna work?

**Comment by r3ggi** [comment]
Hey!

I could not pass `SecCode` to `SecCodeCopySigningInformation` as it expects `SecStaticCode`. However, it works as expected.

If you are developing a new XPC service you should consider using the new API - https://developer.apple.com/documentation/foundation/nsxpcconnection/3943309-setcodesigningrequirement

**Comment by balazserdeszlogmein** [comment]
Thanks for the fast answer!

Sadly, the new macOS13 API is not an option, we are supporting older OS-es.

But you are probably right, the `SecCodeCopySigningInformation` documentation says this for the `code` parameter:

> The **code or static code** object from whose signature you wish to retrieve information. If you provide a code object, the function processes it in the same manner as the [SecCodeCopyStaticCode(_:_:_:)](https://developer.apple.com/documentation/security/1401695-seccodecopystaticcode) function—that is, the static code signing information is obtained from the signature on disk. Note that dynamic information ([kSecCSDynamicInformation](https://developer.apple.com/documentation/security/kseccsdynamicinformation)) can be obtained only for a code object, not for a static code object.

which I would interpret as passing the `kSecCSDynamicInformation` is possible if you converted a `SecCode` to `SecStaticCode`. Especially, since in objective-C the two typedefs have the same underlying type:

```
typedef const struct __SecCode *SecStaticCodeRef;
```
and
```
typedef struct __SecCode SecCodeRef;
```

This looks like a shortfall on Apple's side, either on not allowing SecCode to be passed in Swift, or allowing SecCode to be passed in Objective-C.

Nevertheless, thanks for the fast response! And thanks for this great example, it's a superb starting point in securing XPC in older versions of macOS.

**Comment by r3ggi** [comment]
You're welcome!

BTW - if you'd like me to do take a look at your macOS app security, feel free to reach me out - https://www.linkedin.com/in/wojciech-regula/
